// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResultExn = require("rescript-result-exn/lib/js/src/ResultExn.bs.js");

const parser = require('node-html-parser');
;

var parse = (function (str) {
  return parser.parse(str);
});

var trimRightMut = (function (htmlEl) {
  return htmlEl.trimRight();
});

var removeWhitespaceMut = (function (htmlEl) {
  return htmlEl.removeWhitespace();
});

function querySelectorAll(htmlElement, selector) {
  return ResultExn.catchExn(function (param) {
              var qsa = (function (htmlEl, selector) {
      const res = htmlEl.querySelectorAll(selector);
      if(!Array.isArray(res)) {
        return [res];
      }
      return res;
    });
              return qsa(htmlElement, selector);
            });
}

function getElementsByTagName(htmlElement, selector) {
  var qsa = (function (htmlEl, selector) {
      const res = htmlEl.getElementsByTagName(selector);
      if(!Array.isArray(res)) {
        return [res];
      }
      return res;
    });
  return qsa(htmlElement, selector);
}

function querySelector(htmlElement, selector) {
  return ResultExn.catchExn(function (param) {
              var qsa = (function (htmlEl, selector) {
      const res = htmlEl.querySelector(selector);
      return res;
    });
              return qsa(htmlElement, selector);
            });
}

function closest(htmlElement, selector) {
  return ResultExn.catchExn(function (param) {
              var qsa = (function (htmlEl, selector) {
      const res = htmlEl.closest(selector);
      return res;
    });
              return qsa(htmlElement, selector);
            });
}

var toString = (function(htmlEl) {
  return htmlEl.toString();
});

function insertAdjacentHtmlMut(htmlElement, where, html) {
  return ResultExn.catchExn(function (param) {
              var res = (function (htmlEl, where, html) {
      return htmlEl.insertAdjacentHTML(where, html);
    });
              return res(htmlElement, where, html);
            });
}

function setAttributesMut(htmlElement, attrs) {
  var buildAttrObj = (function (attrs) {
    let res = {};
    attrs.forEach( a => {
      res[a[0]] = a[1];
    } );
    return res;
  });
  var setAttr = (function (htmlEl, attrs) {
    return htmlEl.setAttributes(attrs);
  });
  return setAttr(htmlElement, buildAttrObj(attrs));
}

var replaceWithMut = (function (htmlEl, strs) {
  return htmlEl.replaceWith(strs);
});

var removeMut = (function (htmlEl) {
  return htmlEl.remove();
});

var outerHtml = (function (htmlEl) {
  return htmlEl.outerHTML;
});

var innerHtml = (function (htmlEl) {
  return htmlEl.innerHTML;
});

var tagName = (function (htmlEl) {
  return htmlEl.tagName;
});

var attributes = (function (htmlEl) {
  return {...htmlEl.attributes};
});

exports.parse = parse;
exports.trimRightMut = trimRightMut;
exports.removeWhitespaceMut = removeWhitespaceMut;
exports.querySelectorAll = querySelectorAll;
exports.getElementsByTagName = getElementsByTagName;
exports.querySelector = querySelector;
exports.closest = closest;
exports.toString = toString;
exports.insertAdjacentHtmlMut = insertAdjacentHtmlMut;
exports.setAttributesMut = setAttributesMut;
exports.replaceWithMut = replaceWithMut;
exports.removeMut = removeMut;
exports.outerHtml = outerHtml;
exports.innerHtml = innerHtml;
exports.tagName = tagName;
exports.attributes = attributes;
/*  Not a pure module */
